// Document and collaborator types are generated by Convex after `npx convex dev`.
// Import them directly from the generated data model:
//
//   import type { Doc, Id } from '@/convex/_generated/dataModel'
//   type Document = Doc<'documents'>
//
// The SaveStatus type below is still used by the editor.

export type SaveStatus = 'saved' | 'saving' | 'error' | 'idle'
